# Generated by Django 5.0.6 on 2024-06-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0014_addlaboratories_dentalwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Staffid', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=100)),
                ('Address', models.TextField(max_length=1000)),
                ('Date_of_birth', models.DateField()),
                ('Staff_type', models.CharField(max_length=1000)),
                ('Staf_role', models.CharField(max_length=1000)),
                ('Date_of_joining', models.DateField()),
                ('Password', models.CharField(max_length=1000)),
            ],
        ),
    ]
