# Generated by Django 5.0.6 on 2024-06-04 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0016_policies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Policies',
        ),
    ]
