# Generated by Django 5.0.6 on 2024-06-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0018_policies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policies',
            name='Description',
            field=models.TextField(max_length=100),
        ),
    ]
