# Generated by Django 5.0.6 on 2024-06-04 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0020_webappointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Webappointment',
        ),
    ]
