# Generated by Django 5.0.6 on 2024-06-05 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0022_webappointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Webappointment',
        ),
    ]
