# Generated by Django 5.0.6 on 2024-06-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0023_delete_webappointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webappointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor', models.CharField(max_length=50)),
                ('Patient_name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=50)),
                ('Duration', models.IntegerField(max_length=50)),
                ('Date', models.DateField(max_length=50)),
                ('Time', models.TimeField(max_length=50)),
                ('Treatment', models.CharField(max_length=50)),
            ],
        ),
    ]
