# Generated by Django 5.0 on 2024-06-11 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0024_webappointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_patients',
        ),
    ]
