# Generated by Django 5.0 on 2024-06-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0026_add_patients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_patients',
            name='AreUPregnent',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='add_patients',
            name='PatientUnderAnyMedication',
            field=models.BooleanField(default=True),
        ),
    ]
