# Generated by Django 5.0 on 2024-06-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0027_alter_add_patients_areupregnent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_patients',
            name='AreUPregnent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='add_patients',
            name='PatientUnderAnyMedication',
            field=models.BooleanField(default=False),
        ),
    ]
