# Generated by Django 5.0 on 2024-06-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0028_alter_add_patients_areupregnent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_patients',
            name='ResidentIdNo',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
