# Generated by Django 5.0 on 2024-06-12 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0029_alter_add_patients_residentidno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_patients',
        ),
    ]
