# Generated by Django 5.0 on 2024-06-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0030_delete_add_patients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Register_id', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=10)),
                ('First_name', models.CharField(max_length=1000)),
                ('Last_name', models.CharField(max_length=10)),
                ('Record_no', models.IntegerField(null=True)),
                ('Mobile_no', models.CharField(max_length=100, null=True)),
                ('Email', models.EmailField(max_length=1000, null=True)),
                ('State', models.CharField(max_length=1000, null=True)),
                ('City', models.CharField(max_length=1000, null=True)),
                ('Address', models.TextField(max_length=10000, null=True)),
                ('Date_of_birth', models.DateField()),
                ('Age', models.IntegerField()),
                ('Phone_no', models.CharField(max_length=100, null=True)),
                ('Guardian_name', models.CharField(max_length=100, null=True)),
                ('Op_no', models.IntegerField(null=True)),
                ('Passport_no', models.CharField(max_length=100, null=True)),
                ('Date_of_discharge', models.DateField()),
                ('Gender', models.CharField(max_length=100)),
                ('ResidentIdNo', models.IntegerField(max_length=100, null=True)),
                ('Currentdatetime', models.DateTimeField()),
                ('Genotype', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100, null=True)),
                ('zip_code', models.IntegerField(max_length=100)),
                ('Locality', models.CharField(max_length=100)),
                ('Blood_group', models.CharField(max_length=100, null=True)),
                ('Paitient_remark', models.CharField(max_length=100, null=True)),
                ('Medical_history', models.CharField(max_length=1000, null=True)),
                ('Paitient_group', models.TextField(max_length=1000, null=True)),
                ('Medical_condititon', models.CharField(max_length=1000, null=True)),
                ('Type', models.CharField(max_length=100, null=True)),
                ('Consultation_fee', models.IntegerField()),
                ('AreUPregnent', models.BooleanField(default=False)),
                ('PatientUnderAnyMedication', models.BooleanField(default=False)),
                ('Reffered_by', models.CharField(max_length=1000, null=True)),
                ('Occupation', models.CharField(max_length=100, null=True)),
                ('Photo', models.FileField(upload_to='')),
                ('Doctor', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
