# Generated by Django 5.0 on 2024-06-12 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0031_add_patients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_patients',
        ),
    ]
