# Generated by Django 5.0 on 2024-06-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0033_add_patients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vaccine_name', models.CharField(max_length=100)),
                ('Vaccine_type', models.CharField(max_length=100)),
                ('From_date', models.DateField()),
                ('Todate', models.DateField()),
            ],
        ),
    ]
